# Generated by Django 4.1.5 on 2023-01-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myid', models.CharField(max_length=100)),
                ('deviceModel', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=300)),
                ('serial', models.CharField(max_length=100)),
            ],
        ),
    ]
